export const strings = {
  appName: 'Enterprise Launchpad',
  signInWithSsoButton: 'Sign in with SSO',
  logoutButton: 'Sign out',
  catalogNav: 'Catalog',
  adminNav: 'Admin',
  searchPlaceholder: 'Search services…',
  noResultsTitle: "We couldn't find that service.",
  noResultsHint: 'Try browsing a category, or contact the help desk.',
  favoriteAdd: 'Add to favorites',
  favoriteRemove: 'Remove from favorites',
  launchNotConfiguredHint: "This service isn't set up yet — contact the help desk.",
  adminConsoleTitle: 'Admin Console',
  emptyEntitlementsTitle: 'No services yet',
  emptyEntitlementsHint: 'Contact the help desk if you believe this is a mistake.',
  loadingLabel: 'Loading…',
  categoryFilterLabel: 'Filter by category',
  categoryFilterAll: 'All',
  categoryLabel: 'Category',
  browseCategoryLabel: 'Browse a category:',
  requestServiceButton: 'Request a new service',
  stillStuckPrefix: 'Still stuck? Contact the',
  helpDeskLinkText: 'help desk',
  nameLabel: 'Name',
  descriptionLabel: 'Description',
  supportContactLabel: 'Support contact',
  departmentLabel: 'Department',
  aliasLabel: 'Alias',
  createServiceButton: 'Create service',
  addEntitlementButton: 'Add entitlement',
  addAliasButton: 'Add alias',
  deactivateButton: 'Deactivate',
  activateButton: 'Activate',
  retireButton: 'Retire',
  hideButton: 'Hide',
  manageEntitlementsAliasesButton: 'Manage entitlements/aliases',
  statusLabel: 'Status',
  actionsLabel: 'Actions',
  addEntitlementAriaPrefix: 'Add entitlement to',
  addAliasAriaPrefix: 'Add alias to',
  loadErrorTitle: "We couldn't load this page.",
  loadErrorHint: 'Try again in a moment. If it keeps happening, contact the help desk.',
  retryButton: 'Try again',
  entitlementsHeading: 'Entitlements',
  aliasesHeading: 'Aliases',
  noEntitlementsMessage: 'No entitlements yet — this service is visible to nobody.',
  noAliasesMessage: 'No aliases yet.',
  removeButton: 'Remove',
  anyDepartmentLabel: 'Any department',
  anyRoleLabel: 'Any role',
  ssoTargetLabel: 'SSO Target',
  ssoTargetNone: 'None',
  ssoTargetDemoAppA: 'Demo App A',
  ssoTargetDemoAppB: 'Demo App B',
  launchUrlLabel: 'Launch URL',
  saveButton: 'Save',
};
